// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const imageManifest: Record<string, { base: string; width: number; height: number; widths: number[] }> = {
  "/images/ENTEC.png": {
    "base": "/images/r/ENTEC",
    "width": 1682,
    "height": 311,
    "widths": [
      480,
      768,
      1080,
      1440,
      1682
    ]
  },
  "/images/entec-about.webp": {
    "base": "/images/r/entec-about",
    "width": 2400,
    "height": 448,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920,
      2400
    ]
  },
  "/images/aboutimg.webp": {
    "base": "/images/r/aboutimg",
    "width": 2400,
    "height": 507,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920,
      2400
    ]
  },
  "/images/about.webp": {
    "base": "/images/r/about",
    "width": 2000,
    "height": 856,
    "widths": [
      480,
      768,
      1080,
      1440,
      1920,
      2000
    ]
  },
  "/images/team1.webp": {
    "base": "/images/r/team1",
    "width": 900,
    "height": 900,
    "widths": [
      480,
      768,
      900
    ]
  },
  "/images/team2.webp": {
    "base": "/images/r/team2",
    "width": 900,
    "height": 900,
    "widths": [
      480,
      768,
      900
    ]
  },
  "/images/team3.webp": {
    "base": "/images/r/team3",
    "width": 900,
    "height": 900,
    "widths": [
      480,
      768,
      900
    ]
  },
  "/images/team4.webp": {
    "base": "/images/r/team4",
    "width": 900,
    "height": 900,
    "widths": [
      480,
      768,
      900
    ]
  },
  "/images/blogs/design-process.webp": {
    "base": "/images/r/blogs-design-process",
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      768,
      1024
    ]
  },
  "/images/blogs/design-value.webp": {
    "base": "/images/r/blogs-design-value",
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      768,
      1024
    ]
  },
  "/images/blogs/future-trends.webp": {
    "base": "/images/r/blogs-future-trends",
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      768,
      1024
    ]
  },
  "/images/blogs/minimalism.webp": {
    "base": "/images/r/blogs-minimalism",
    "width": 1024,
    "height": 1024,
    "widths": [
      480,
      768,
      1024
    ]
  }
};
