// Builds responsive, high-quality WebP copies of the large site images into public/images/r/
// and writes lib/imageManifest.ts (sizes for <img srcset>). Run after adding/replacing an image:
//   node scripts/optimize-images.mjs
// Quality is kept high (q90, full-quality alpha) — the savings come from serving each screen an
// image that matches its size instead of one huge file, not from lowering quality.
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const outDir = path.join(root, "public/images/r");
fs.mkdirSync(outDir, { recursive: true });

const WIDTHS = [480, 768, 1080, 1440, 1920, 2400];
const SOURCES = [
  "ENTEC.png",
  "entec-about.webp",
  "aboutimg.webp",
  "about.webp",
  "team1.webp",
  "team2.webp",
  "team3.webp",
  "team4.webp",
  "blogs/design-process.webp",
  "blogs/design-value.webp",
  "blogs/future-trends.webp",
  "blogs/minimalism.webp",
];

const manifest = {};
for (const rel of SOURCES) {
  const src = path.join(root, "public/images", rel);
  const meta = await sharp(src).metadata();
  const base = rel.replace(/\.[a-z]+$/i, "").replace(/\//g, "-");
  const widths = WIDTHS.filter((w) => w < meta.width).concat(meta.width);
  for (const w of widths) {
    const file = path.join(outDir, `${base}-${w}.webp`);
    // Full size of a source that is already WebP: an exact copy, never re-compressed
    if (w === meta.width && meta.format === "webp") {
      fs.copyFileSync(src, file);
      continue;
    }
    await sharp(src)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 90, alphaQuality: 100, effort: 6, smartSubsample: true })
      .toFile(file);
  }
  manifest["/images/" + rel] = { base: `/images/r/${base}`, width: meta.width, height: meta.height, widths };
  console.log(rel, widths.join(","));
}

// Soft, blurred background artwork: no detail to lose, so it is re-encoded smaller as-is
for (const [rel, w, q] of [["aboutbac.webp", 1600, 82]]) {
  const src = path.join(root, "public/images", rel);
  const out = path.join(outDir, rel);
  await sharp(src).resize({ width: w, withoutEnlargement: true }).webp({ quality: q, alphaQuality: 70, effort: 6 }).toFile(out);
  console.log(rel, "->", Math.round(fs.statSync(out).size / 1024) + "KB");
}

fs.writeFileSync(
  path.join(root, "lib/imageManifest.ts"),
  "// Generated by scripts/optimize-images.mjs — do not edit by hand.\n" +
    "export const imageManifest: Record<string, { base: string; width: number; height: number; widths: number[] }> = " +
    JSON.stringify(manifest, null, 2) +
    ";\n",
);
